spring.application.name=stegvis-api
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=stegvis
# spring.data.mongodb.uri=mongodb+srv://favigx:${ATLASPASSWORD}@cluster0.u8unxhm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
jwtSecret=${JWTSECRET}
jwt.expiration= 3600000
